/*****************************************************************************
 *  Generated by Slider's 'Roomy for Windows' v0.8
 *  room created 11-05-1994 at 18:11:47
 ****************************************************************************/

#include "/players/slider/include/slider.h"

inherit "room/room";
reset(arg)
{

   if (arg) return;
}

create() {
   set_short("Slider's Bathroom");

   set_long("\
This is Slider's bathroom. Plush, dark green carpeting covers the floors, and\n\
a massive sunken hot tub dominates one corner of the room. A TV set is built\n\
into the wall opposite the hot tub. A tandem toilet stands in another corner,\n\
with a bookshelf and magazine rack within easy reach. A doorway leads south\n\
into the den.\n\
   ");

   add_exit(ROOMS+"den","south");

   add_item("bookshelf", "\
It's fully populated with decent crapper reading - The Book Of Lists,\n\
Guinness Book of World Records, and some trashy novel about Led Zeppelin.\
   ");

   add_item("magazine", "\
There are a bunch of old Playboys here, as well as Spy, Rolling Stone, and a\n\
smaller one called 2600.\
   ");
 
   add_item("cabinet", "\
It's filled with videotapes. You read some of the titles: Caddyshack, Repo\n\
Man, Rocky Horror, Apocalypse Now. Here's one with a handwritten label \n\
titled 'Kids In The Hall Marathon', another labeled 'Ren & Stimpy!'\n\
   ");
 

   add_item("rack", "\
It's groaning from the weight of all the magazines. There are a bunch of old\n\
Playboys here, as well as Spy, Rolling Stone, and a smaller one called 2600.\
   ");

   add_item("shelf", "\
It's fully populated with decent crapper reading - The Book Of Lists,\n\
Guinness Book of World Records, and some trashy novel about Led Zeppelin.\
   ");

   add_item("toilet", "\
It's one of those pathetic two-person love toilets with the turbo flush.\n\
Doubtless for when Slider's beloved Xena is hogging the bathroom!\
   ");

   add_item("tv", "\
It's a large Sony built into the wall. A hidden cabinet underneath houses a\n\
VCR and cables.\
   ");

   set_light(1);
   reset(0);
}
