/*****************************************************************************
 *  Generated by Slider's 'Roomy for Windows' v0.8
 *  room created 11-05-1994 at 18:24:58
 ****************************************************************************/

#include "/players/slider/include/slider.h"
inherit "room/room";

reset(arg)
{

   if (arg) return;
}

create() {
   set_short("Slider's Bestiary");

   set_long("\
This is a vast concrete room.  Blood and other less describable stains mar\n\
the walls and floor.  This is Slider's Bestiary, where he perfects his nasty\n\
monsters before releasing them into the realm.  A set of stairs leads up,\n\
and there's a room to the west.\n\
   ");

   add_exit(ROOMS+"den","up");
   add_exit(ROOMS+"control", "west");

   add_item("blood", "\
It looks pretty fresh.  Don't touch it!\
   ");

   add_item("stains", "\
Kind of gross.  Who KNOWS what weird and unfortunate creature left THAT\n\
behind...\
   ");

   add_item("stairs", "\
One of man's earliest attempts at an anti-gravity machine.  In this context,\n\
type 'up' to use this strange and exotic apparatus!\
   ");

   set_light(1);
   reset(0);
}
