/*****************************************************************************
 *  Generated by Slider's 'Roomy for Windows' v0.8
 *  room created 12-29-1993 at 03:17:14
 ****************************************************************************/
 
#include "/players/slider/include/slider.h"
inherit "room/room";
 
reset(arg)
{
 
   if (arg) return;
}
 
create() {
   set_short("Slider's Den");
   set_long("\
This is Slider's dimly lit den.  Overstuffed leather furniture is\n\
everywhere, and soft music emanates from hidden speakers.  There are  still\n\
more boxes in various stages of unpacking scattered about.  A bathroom is\n\
north of here, Slider's workroom is west, a door leads  leads east into the\n\
kitchen, and a set of stairs leads down.\n\
   ");
 
   add_exit(ROOMS+"bathroom","north");
   add_exit("/players/slider/workroom","west");
   add_exit(ROOMS+"kitchen","east");
   add_exit(ROOMS+"bestiary","down");
 
   add_item("box", "\
Some of them look as if they've been through several moves without being\n\
opened!\
   ");
 
   add_item("boxes", "\
Some of them look as if they've been through several moves without being\n\
opened!\
   ");
 
   add_item("furniture", "\
The furniture looks very comfy!\
   ");
 
   add_item("speaker", "\
They're hidden...so you can't see them!\
   ");
 
   add_item("speakers", "\
They're hidden...so you can't see them!\
   ");
 
   set_light(1);
   reset(0);
}
