/*****************************************************************************
 *  Generated by Slider's 'Roomy for Windows' v0.8
 *  room created 02-22-1996 at 15:29:41
 *  Modified for Barrowmere 6/5/97 - Frij
    9/17/2003  Slider   Changed description slightly - "portal to Barrowmere"
 ****************************************************************************/

#include "/players/slider/include/slider.h"

inherit "room/room";
reset(arg)
{

   if(!present("teller"))
      move_object(clone_object(OBJ+"bankmach"), this_object());

   if (arg) return;
}

create() {
	set_short("Barrowmere Bank");

   set_long("\
You are standing in a very nice looking bank full of marble pillars and\n\
floors. This bank must generate lots of money. A strange machine stands\n\
before you, eager to take your money or to give you some back. To the east\n\
lies a shimmering portal that leads to the city of Barrowmere.
   ");

        add_exit("/players/slider/rooms/elwood02", "south");
	add_exit("/room/circ/main5","east");

   add_item("ad", "\
The ad reads 'Totally FREE checking! Ask a teller!'.\
   ");

   add_item("advertisement", "\
The ad reads 'Totally FREE checking! Ask a teller!'.\
   ");

   add_item("portal", "\
It's blue, it's shimmery....you know the drill!\
   ");

   set_light(1);
   reset(0);
}
