/*****************************************************************************
 *  Generated by Roomie for Windows v0.6
 *  room created 12-29-1993
 ****************************************************************************/
 
#include "/players/slider/include/slider.h"
 
inherit "room/room";
reset(arg)
{
 
   if (arg) return;
}
 
create() {
   set_short("Dark Alley");
   set_long("\
This is a dark, trash strewn alley just off from a side street in the village\n\
of Elwoode.  The stench here is enough to make you wrinkle your nose in\n\
disgust.  The alley continues further to the west and exits to the east.\n\
   ");
 
   add_exit(ROOMS + "elwood04","east");
   add_exit(ROOMS + "elwood4b","west");
 
   add_item("debris", "\
See 'trash'\
   ");
 
   add_item("smell", "\
Yes, the smell is so bad here you can almost see it; a green, hulking cloud\n\
that seems to dare you to breathe through your nose!\
   ");
 
   add_item("stench", "\
Yes, the smell is so bad here you can almost see it; a green, hulking cloud\n\
that seems to dare you to breathe through your nose!\
   ");
 
   add_item("trash", "\
Bits of old newspaper, a piece of a rotting, leftover wyvern-steak\n\
sandwich...not very appealing to either nose or eye.\
   ");
 
   set_light(1);
   reset(0);
}
