/*****************************************************************************
 *  Generated by Slider's 'Roomy for Windows' v0.8
 *  room created 02-16-1996 at 23:34:11
 ****************************************************************************/

#include "/players/slider/include/slider.h";

inherit "room/room";
reset(arg)
{

   if (arg) return;
}

create() {
   set_short("A room");

   set_long("\
This is a large, stark white room. The only thing in the room is a large,\n\
white pedestal that contains a nose.\n\
   ");

   add_exit(ROOMS+"path1","south");

   add_item("nose", "\
A large nose.\
   ");

   add_item("pedestal", "\
It's a large, lighted white pedestal.\
   ");

   set_light(1);
   reset(0);
}
