/*****************************************************************************
 *  Generated by Roomie for Windows v0.6
 *  room created 12-29-1993
 ****************************************************************************/
 
#include "/players/slider/include/slider.h"
inherit "room/room";
 
reset(arg)
{
 
   if (arg) return;
}
 
create() {
   set_short("Tunnel Cave In");
   set_long("\
You've come to the dead end of this branch of the tunnel.  Judging from the\n\
looks of the wall in front of you, a cave-in has occurred here rather\n\
recently.  There's  some faint writing scratched onto a rock nearby.\n\
   ");
 
   add_exit(ROOMS+"test3","north");
   add_exit(ROOMS+"testroom","south");
 
   add_item("writing", "\
The writing says: 'The gold is hidden in the....'.  Unfortunately, you can't\n\
make out the rest of the sentence!\
   ");
 
   set_light(1);
   reset(0);
}
