/*****************************************************************************
 *  Generated by Roomie for Windows v0.6
 *  room created 12-29-1993
 ****************************************************************************/
 
#include "/players/slider/include/slider.h"
 
inherit "room/room";
 
reset(arg)
{
 
   if (arg) return;
}
 
create() {
   set_short("Test Room 3");
   set_long("\
This is a test room.  There's not much of interest here at all.  There's a\n\
small sign here.\n\
   ");
 
   add_exit(ROOMS+"test2","south");
 
   add_item("sign", "\
Hey!  You've read me.  Good thinking!\
   ");
 
   set_light(1);
   reset(0);
}
