/*****************************************************************************
 *  Generated by Roomie for Windows v0.6
 *  room created 12-29-1993
 ****************************************************************************/
 
#include "/players/slider/include/slider.h"
inherit "room/room";
 
reset(arg)
{
 
   if (arg) return;
}
 
create() {
   set_short("Sample Room");
   set_long("\
This is a sample room that was generated using Slider's way cool room\n\
generator for Microsoft Windows.  This room generator is cool because it not\n\
only GENERATES rooms, but it can read in existing room files as well.  Cool,\n\
eh?  Oh yeah, there's a thing and an item here.\n\
   ");
 
   add_exit(ROOMS+"test2","north");
   add_exit("/players/slider/workroom.c","south");
 
   add_item("item", "\
This is an item.  You can look at it, but it doesn't really exist, since it's\n\
just a description and not an actual object.\
   ");
 
   add_item("thing", "\
This is a thing.  This is not real, either, although you can pretend it is.\n\
Remember, this is only a game!\
   ");
 
   set_light(1);
   reset(0)  //*** deliberate error to check update ***
}
