/*****************************************************************************
 *  Generated by Slider's 'Roomy for Windows' v0.8
 *  room created 06-08-1995 at 14:33:54
 ****************************************************************************/

#include "/players/slider/include/slider.h"

inherit "room/room";

reset(arg)
{

   if (arg) return;
}

create() {
   set_short("Scenic Turnout");

   set_long("\
You've reached a scenic turnout off the main trail. The turnout is actually a\n\
small cliff that overlooks the river valley. The river courses far  below\n\
your current position, and you can see for miles in all directions. A  pair\n\
of coin-operated binoculars is mounted on a stand. A scrap of paper lies at\n\
the base of the binoculars. A narrow, overgrown  path winds back up south to\n\
the trail.\n\
   ");

   add_exit(ROOMS+"trails001","south");

   add_item("binoculars", "\
A pair of coin-operated binoculars is mounted on a stand here.\
   ");

   add_item("paper", "\
A scrap of paper. The word 'minuet47' is scrawled in faded handwriting on it.\
   ");

   add_item("scrap", "\
A scrap of paper. The word 'minuet47' is scrawled in faded handwriting on it.\
   ");

   set_light(1);
   reset(0);
}
